version: '3.4'

services:
  pipeline:
    container_name: vre_pipeline_1
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    tty: true
    entrypoint: ["/vurm/scripts/run-pipeline-dkr.sh"]