version: '3.4'

services:

  dreamfactory:
    build: dreamfactory
    ports:
      - "8089:80"
    links:
      - postgres
    env_file:
      - .env
    environment:
      - DB_SERVICES_HOST=postgres
      - DB_SERVICES_PORT=5432  
      - DB_OBJECTS_HOST=postgres
      - DB_OBJECTS_PORT=5432  
    tty: true  
      
  postgres:
    build: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

