version: '3.4'

services:
  integration:
    build: ./integration
    volumes:
      - ./integration:/usr/local/integration

  tagger:
    command: ./docker/docker-run-tagger.sh
    volumes:
      - ./tagger:/usr/local/tagger
    environment:
      KAFKA_BROKER: localhost
      KAFKA_PORT: ${KAFKA_PORT}
      RECOGNIZER_TOPIC_NAME: ${RECOGNIZER_TOPIC_NAME}
      RECOGNIZER_GROUP_NAME: ${RECOGNIZER_GROUP_NAME}
      TAGGER_TOPIC_NAME: ${TAGGER_TOPIC_NAME}
      TAGGER_GROUP_NAME: ${TAGGER_TOPIC_NAME}
      USER_OBJECTS_EMAIL: ${USER_OBJECTS_EMAIL}
      USER_OBJECTS_PASSWORD: ${USER_OBJECTS_PASSWORD}
      APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}
      TEST_USER: ${TEST_USER}
      TEST_PASSWORD: ${TEST_PASSWORD}

  switchboard:
    build: ./switchboard/docker
    command: ./docker/docker-run-switchboard.sh
    volumes:
      - ./switchboard:/usr/local/switchboard
    links:
      - dreamfactory
      - deployment
    environment:
      APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}
      APP_KEY_SERVICES: ${APP_KEY_SERVICES}

  nextcloud:
    build: ./nextcloud
    volumes:
      - data-volume:/var/www/html/data
    networks:
      default:
        aliases:
          - nextcloud

  recognizer:
    build: ./recognizer/recognizer
    volumes:
      - ./recognizer:/usr/local/recognizer
      - data-volume:/tmp/recognizer
    links:
      - dreamfactory:dreamfactory
    environment:
      USER_OBJECTS_EMAIL: ${USER_OBJECTS_EMAIL}
      USER_OBJECTS_PASSWORD: ${USER_OBJECTS_PASSWORD}
      APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}

  fits:
    container_name: vre_fits_1
    build: ./recognizer/fits
    volumes:
      - data-volume:/tmp/recognizer

  dreamfactory:
    build: ./registry/dreamfactory
    volumes:
     - ./registry/dreamfactory/config/postgres:/postgres

  postgres:
    container_name: vre_postgres_1
    build: ./registry/postgres

  trifecta:
    container_name: vre_trifecta_1
    image: janschultecom/docker-trifecta
    ports:
      - 9000:9000
    environment:
      ZK_HOST: zookeeper:2181
    depends_on:
      - zookeeper
    links:
      - zookeeper

  zookeeper:
    image: zookeeper:3.4

  deployment:
    build: ./deployment-service
    volumes:
      - ./deployment-service/conf:/conf
      - deployment-volume:/tmp/wd/
      - data-volume:/usr/local/nextcloud
      # share maven repository of host:
      - maven-m2:/root/.m2/repository
    depends_on:
      - dreamfactory
    environment:
      USER_SERVICES_EMAIL: ${USER_SERVICES_EMAIL}
      USER_SERVICES_PASSWORD: ${USER_SERVICES_PASSWORD}
      APP_KEY_SERVICES: ${APP_KEY_SERVICES}
    ports:
      - 9999:8080

  indexer:
    build: ./indexer/indexer
    volumes:
      - ./indexer:/usr/local/indexer
    links:
      - dreamfactory:dreamfactory
    environment:
      USER_OBJECTS_EMAIL: ${USER_OBJECTS_EMAIL}
      USER_OBJECTS_PASSWORD: ${USER_OBJECTS_PASSWORD}
      APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}
      
  solr:
    container_name: vre_solr_1
    build: ./indexer/solr
    volumes:
      - data-volume:/storage      
  
  lamachine:
    container_name: vre_lamachine_1
    build: ./lamachine
    tty: true
    command: /start-web.sh
    ports:
      - 9998:80

volumes:
  data-volume:
  maven-m2:
  deployment-volume:
