version: '3.4'

# Root compose file of components to overwrite relative volume and build paths

services:
  integration:
    build: ./integration
    volumes:
      - ./integration:/usr/local/integration

  tagger:
    volumes:
      - ./tagger:/usr/local/tagger

  switchboard:
    build: ./switchboard/docker
    volumes:
      - ./switchboard:/usr/local/switchboard
    depends_on:
      - dreamfactory
      - deployment
    environment:
      APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}
      APP_KEY_SERVICES: ${APP_KEY_SERVICES}

  nextcloud:
    build: ./nextcloud
    volumes:
      - data-volume:/var/www/html/data
    networks:
      default:
        aliases:
          - nextcloud

  recognizer:
    build: ./recognizer/recognizer
    volumes:
      - ./recognizer:/usr/local/recognizer
      - data-volume:/tmp/recognizer
    depends_on:
      - dreamfactory
    environment:
      USER_OBJECTS_EMAIL: ${USER_OBJECTS_EMAIL}
      USER_OBJECTS_PASSWORD: ${USER_OBJECTS_PASSWORD}
      APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}

  fits:
    container_name: vre_fits_1
    build: ./recognizer/fits
    volumes:
      - data-volume:/tmp/recognizer

  dreamfactory:
    build: ./registry/dreamfactory
    volumes:
     - ./registry/dreamfactory/config/postgres:/postgres

  postgres:
    container_name: vre_postgres_1
    build: ./registry/postgres

  trifecta:
    container_name: vre_trifecta_1
    image: janschultecom/docker-trifecta
    ports:
      - 9000:9000
    environment:
      ZK_HOST: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.4

  deployment:
    build: ./deployment-service
    volumes:
      - ./deployment-service/conf:/conf
      - ./deployment-service/:/tmp/deployment
      - deployment-volume:/tmp/wd/
      - data-volume:/usr/local/nextcloud
      # share maven repository of host:
      - maven-m2:/root/.m2/repository
    depends_on:
      - dreamfactory
      - tika
    environment:
      USER_SERVICES_EMAIL: ${USER_SERVICES_EMAIL}
      USER_SERVICES_PASSWORD: ${USER_SERVICES_PASSWORD}
      APP_KEY_SERVICES: ${APP_KEY_SERVICES}
    ports:
      - 9999:8080

  indexer:
    build: ./indexer/indexer
    volumes:
      - ./indexer:/usr/local/indexer
    depends_on:
      - dreamfactory
    environment:
      USER_OBJECTS_EMAIL: ${USER_OBJECTS_EMAIL}
      USER_OBJECTS_PASSWORD: ${USER_OBJECTS_PASSWORD}
      APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}
      
  solr:
    container_name: vre_solr_1
    build: ./indexer/solr
    volumes:
      - data-volume:/storage      
  
  lamachine:
    container_name: vre_lamachine_1
    build: ./lamachine
    tty: true
    command: /start-web.sh
    ports:
      - 9998:80

  tika:
    image: logicalspark/docker-tikaserver:1.20

volumes:
  data-volume:
  maven-m2:
  deployment-volume:
