#!/bin/bash
set -e

printf "# Do not edit directly, generated by ./merge-containers.sh \n\n" \
  >  docker-compose.yml

# Merge compose files of different components into docker-compose-tmp.yml
# - add new compose file after blank and before override
docker-compose \
  -f ./docker-compose-blank.yml \
  -f ./integration/docker-compose.yml \
  -f ./nextcloud/docker-compose.yml \
  -f ./recognizer/docker-compose.yml \
  -f ./registry/docker-compose.yml \
  -f ./switchboard/docker-compose.yml \
  -f ./indexer/docker-compose.yml \
  -f ./deployment-service/docker-compose.yml \
  -f ./tagger/docker-compose.yml \
  -f ./docker-compose-override.yml \
  config >> docker-compose.yml
