FROM proycon/lamachine

ADD ./start-web.sh /start-web.sh
#ADD ./settings.py /usr/local/src/flat/settings.py
#ADD ./latest.yml /lamachine/host_vars/latest.yml
#ADD ./localhost.yml /lamachine/host_vars/localhost.yml
#ADD ./flat_settings.py /usr/local/etc/flat_settings.py

## enable the next line to debug ucto in lamachine
# ADD ./ucto.py /usr/local/src/clamservices/clamservices/config/ucto.py