version: '3.4'

services:
  deployment:
    container_name: vre_deployment_1
    image: knawhuc/clariah-wp3-vre-deployment:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    tty: true
