version: '3.4'

services:
  recognizer:
    build: ./recognizer
    tty: true
    working_dir: /usr/local/recognizer
    command: ./docker-run-recognizer.sh
    expose:
      - 80
    volumes:
      - ./:/usr/local/recognizer
      # share maven repository of host:
      - ${HOME}/.m2/repository:/root/.m2/repository
    depends_on:
      - fits
      - kafka
    extra_hosts:
     - moby:127.0.0.1
    links:
      - fits:fits
      - kafka:kafka
    environment:
      KAFKA_BROKER: localhost
      FITS_FILES_ROOT: ${FITS_FILES_ROOT}
      KAFKA_PORT: ${KAFKA_PORT}
      OWNCLOUD_TOPIC_NAME: ${OWNCLOUD_TOPIC_NAME}
      OWNCLOUD_GROUP_NAME: ${OWNCLOUD_GROUP_NAME}
      RECOGNIZER_TOPIC_NAME: ${RECOGNIZER_TOPIC_NAME}
      RECOGNIZER_GROUP_NAME: ${RECOGNIZER_GROUP_NAME}

  fits:
    build: ./fits
    volumes:
      - /tmp/recognizer:/tmp/recognizer
    extra_hosts:
      - moby:127.0.0.1
#    ports:
#      - 8080:8080

  kafka:
    image: wurstmeister/kafka:1.0.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    extra_hosts:
     - moby:127.0.0.1
    ports:
      - ${KAFKA_PORT}

  zookeeper:
    image: zookeeper:3.4
