version: '3.4'

services:
  recognizer:
    container_name: vre_recognizer_1
    image: knawhuc/clariah-wp3-vre-recognizer:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        KAFKA_BROKER: localhost
        FITS_FILES_ROOT: ${FITS_FILES_ROOT}
        KAFKA_PORT: ${KAFKA_PORT}
        NEXTCLOUD_TOPIC_NAME: ${NEXTCLOUD_TOPIC_NAME}
        NEXTCLOUD_GROUP_NAME: ${NEXTCLOUD_GROUP_NAME}
        RECOGNIZER_TOPIC_NAME: ${RECOGNIZER_TOPIC_NAME}
        RECOGNIZER_GROUP_NAME: ${RECOGNIZER_GROUP_NAME}
        USER_OBJECTS_EMAIL: ${USER_OBJECTS_EMAIL}
        USER_OBJECTS_PASSWORD: ${USER_OBJECTS_PASSWORD}
        APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}
    tty: true
    expose:
    - 80
    depends_on:
    - fits
    - kafka
    extra_hosts:
    - moby:127.0.0.1
    environment:
      KAFKA_BROKER: localhost
      FITS_FILES_ROOT: ${FITS_FILES_ROOT}
      KAFKA_PORT: ${KAFKA_PORT}
      NEXTCLOUD_TOPIC_NAME: ${NEXTCLOUD_TOPIC_NAME}
      NEXTCLOUD_GROUP_NAME: ${NEXTCLOUD_GROUP_NAME}
      RECOGNIZER_TOPIC_NAME: ${RECOGNIZER_TOPIC_NAME}
      RECOGNIZER_GROUP_NAME: ${RECOGNIZER_GROUP_NAME}
      USER_OBJECTS_EMAIL: ${USER_OBJECTS_EMAIL}
      USER_OBJECTS_PASSWORD: ${USER_OBJECTS_PASSWORD}
      APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}

  fits:
    build: ./fits
    volumes:
    - /tmp/recognizer:/tmp/recognizer
    extra_hosts:
    - moby:127.0.0.1

  kafka:
    image: wurstmeister/kafka:1.0.0
    depends_on:
    - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 1200000
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 1200000
    extra_hosts:
    - moby:127.0.0.1
    ports:
    - ${KAFKA_PORT}

  zookeeper:
    image: zookeeper:3.4
