version: '3.4'

services:
  tagger:
    container_name: vre_tagger_1
    image: knawhuc/clariah-wp3-vre-tagger:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        KAFKA_PORT: ${KAFKA_PORT}
        RECOGNIZER_TOPIC_NAME: ${RECOGNIZER_TOPIC_NAME}
        RECOGNIZER_GROUP_NAME: ${RECOGNIZER_GROUP_NAME}
        TAGGER_TOPIC_NAME: ${TAGGER_TOPIC_NAME}
        TAGGER_GROUP_NAME: ${TAGGER_TOPIC_NAME}
        APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}
        TEST_USER: ${TEST_USER}
        TEST_PASSWORD: ${TEST_PASSWORD}
    expose:
    - 80
    depends_on:
    - kafka
    extra_hosts:
    - moby:127.0.0.1
    environment:
      KAFKA_PORT: ${KAFKA_PORT}
      RECOGNIZER_TOPIC_NAME: ${RECOGNIZER_TOPIC_NAME}
      RECOGNIZER_GROUP_NAME: ${RECOGNIZER_GROUP_NAME}
      TAGGER_TOPIC_NAME: ${TAGGER_TOPIC_NAME}
      TAGGER_GROUP_NAME: ${TAGGER_TOPIC_NAME}
      APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}
      TEST_USER: ${TEST_USER}
      TEST_PASSWORD: ${TEST_PASSWORD}

  kafka:
    image: wurstmeister/kafka:1.0.0
    depends_on:
    - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 1200000
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 1200000
    extra_hosts:
    - moby:127.0.0.1
    ports:
    - ${KAFKA_PORT}

  zookeeper:
    image: zookeeper:3.4
