version: '3.4'

services:
  indexer:
    container_name: vre_indexer_1
    build: ./indexer
    tty: true
    working_dir: /usr/local/indexer
    command: ./docker-run-indexer.sh
    ports:
      - 8088:80
    volumes:
      - ./:/usr/local/indexer
      # share maven repository of host:
      - ${HOME}/.m2/repository:/root/.m2/repository
    depends_on:
      - solr
      - kafka
    extra_hosts:
     - moby:127.0.0.1
    environment:
      KAFKA_BROKER: localhost
      KAFKA_PORT: ${KAFKA_PORT}
      NEXTCLOUD_TOPIC_NAME: ${NEXTCLOUD_TOPIC_NAME}
      NEXTCLOUD_GROUP_NAME: ${NEXTCLOUD_GROUP_NAME}
      RECOGNIZER_TOPIC_NAME: ${RECOGNIZER_TOPIC_NAME}
      RECOGNIZER_GROUP_NAME: ${RECOGNIZER_GROUP_NAME}
      INDEXER_TOPIC_NAME: ${INDEXER_TOPIC_NAME}
      INDEXER_GROUP_NAME: ${INDEXER_GROUP_NAME}
      SOLR_URL: ${SOLR_URL}

  solr:
    build: ./solr
    tty: true
    volumes:
      - ./files:/storage
    ports:
      - 8087:8983

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    extra_hosts:
     - moby:127.0.0.1
    ports:
      - ${KAFKA_PORT}

  zookeeper:
    image: zookeeper:3.4
