version: '3.4'

services:
  nextcloud:
    # image: nextcloud:latest
    build: .
    container_name: vre_nextcloud_1
#    restart: always
    ports:
      - "8082:80"
    extra_hosts:
    - moby:127.0.0.1
    depends_on:
      - kafka
    environment:
      - NEXTCLOUD_APP_NAME=${NEXTCLOUD_APP_NAME}
      - KAFKA_PORT=${KAFKA_PORT}
      - NEXTCLOUD_TOPIC_NAME=${NEXTCLOUD_TOPIC_NAME}
      - NEXTCLOUD_GROUP_NAME=${NEXTCLOUD_GROUP_NAME}
      - NEXTCLOUD_DB_TYPE=${NEXTCLOUD_DB_TYPE}
      - NEXTCLOUD_DB_NAME=${NEXTCLOUD_DB_NAME}
      - NEXTCLOUD_DB_USER=${NEXTCLOUD_DB_USER}
      - NEXTCLOUD_DB_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - NEXTCLOUD_DB_HOST=${NEXTCLOUD_DB_HOST}
      - NEXTCLOUD_ADMIN_NAME=${NEXTCLOUD_ADMIN_NAME}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_DATA_DIR=${NEXTCLOUD_DATA_DIR}
      - TEST_USER=${TEST_USER}
      - TEST_PASSWORD=${TEST_PASSWORD}

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    container_name: vre_kafka_1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 1200000
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 1200000
      KAFKA_ADVERTISED_LISTENERS: DEFAULT_LISTENER://kafka:9092
      KAFKA_LISTENERS: DEFAULT_LISTENER://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DEFAULT_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DEFAULT_LISTENER
    extra_hosts:
     - moby:127.0.0.1
    ports:
      - ${KAFKA_PORT}

  zookeeper:
    image: zookeeper:3.4
    container_name: vre_zookeeper_1
