version: '3.4'

#
# Should not be run stand-alone: needs vre-components
#

services:
  integration:
    container_name: vre_integration_1
    command: tail -f /dev/null # to keep container up
    build: .
    tty: true
    working_dir: /usr/local/integration/
    depends_on:
      - recognizer
      - nextcloud
      - postgres
      - kafka
      - switchboard
      - deployment
      - lamachine
    volumes:
      - ./:/usr/local/integration
      # share maven repository of host:
      - ${HOME}/.m2/repository:/root/.m2/repository
    extra_hosts:
     - moby:127.0.0.1
    environment:
      - KAFKA_PORT=${KAFKA_PORT}
      - NEXTCLOUD_TOPIC_NAME=${NEXTCLOUD_TOPIC_NAME}
      - NEXTCLOUD_GROUP_NAME=${NEXTCLOUD_GROUP_NAME}
      - NEXTCLOUD_ADMIN_NAME=${NEXTCLOUD_ADMIN_NAME}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - FITS_FILES_ROOT=${FITS_FILES_ROOT}
      - RECOGNIZER_TOPIC_NAME=${RECOGNIZER_TOPIC_NAME}
      - TAGGER_TOPIC_NAME=${TAGGER_TOPIC_NAME}
      - DB_OBJECTS_DATABASE=${DB_OBJECTS_DATABASE}
      - DB_OBJECTS_USER=${DB_OBJECTS_USER}
      - DB_OBJECTS_PASSWORD=${DB_OBJECTS_PASSWORD}
      - DB_SERVICES_DATABASE=${DB_SERVICES_DATABASE}
      - DB_SERVICES_USER=${DB_SERVICES_USER}
      - DB_SERVICES_PASSWORD=${DB_SERVICES_PASSWORD}

    ports:
      - "8085:8085"
