version: '3.4'

services:
  switchboard:
    container_name: vre_switchboard_1
    image: knawhuc/clariah-wp3-vre-switchboard:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        SWITCHBOARD_TOPIC_NAME: ${SWITCHBOARD_TOPIC_NAME}
        NEXTCLOUD_TOPIC_NAME: ${NEXTCLOUD_TOPIC_NAME}
        KAFKA_PORT: ${KAFKA_PORT}
        NEXTCLOUD_VOLUME: ${SWITCHBOARD_NEXTCLOUD_VOLUME}
        DEPLOYMENT_VOLUME: ${SWITCHBOARD_DEPLOYMENT_VOLUME}
        TEST_USER: ${TEST_USER}
        TEST_PASSWORD: ${TEST_PASSWORD}
        USER_TO_LOCK_WITH: ${SWITCHBOARD_USER_TO_LOCK_WITH}
        USER_TO_UNLOCK_WITH: ${SWITCHBOARD_USER_TO_UNLOCK_WITH}
        APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}
        APP_KEY_SERVICES: ${APP_KEY_SERVICES}
    tty: true
    extra_hosts:
    - moby:127.0.0.1
    ports:
    - 9010:8080
    depends_on:
    - kafka
    volumes:
    - ./static_files:/user/local/switchboard/static_files
    - data-volume:/usr/local/nextcloud
    - deployment-volume:/tmp/deployment
    - mvn-repo-volume:/usr/local/mvn-repo-volume
    environment:
      SWITCHBOARD_TOPIC_NAME: ${SWITCHBOARD_TOPIC_NAME}
      NEXTCLOUD_TOPIC_NAME: ${NEXTCLOUD_TOPIC_NAME}
      KAFKA_PORT: ${KAFKA_PORT}
      NEXTCLOUD_VOLUME: ${SWITCHBOARD_NEXTCLOUD_VOLUME}
      DEPLOYMENT_VOLUME: ${SWITCHBOARD_DEPLOYMENT_VOLUME}
      TEST_USER: ${TEST_USER}
      TEST_PASSWORD: ${TEST_PASSWORD}
      USER_TO_LOCK_WITH: ${SWITCHBOARD_USER_TO_LOCK_WITH}
      USER_TO_UNLOCK_WITH: ${SWITCHBOARD_USER_TO_UNLOCK_WITH}
      APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}
      APP_KEY_SERVICES: ${APP_KEY_SERVICES}

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    depends_on:
    - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: DEFAULT_LISTENER://kafka:9092
      KAFKA_LISTENERS: DEFAULT_LISTENER://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DEFAULT_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DEFAULT_LISTENER
    extra_hosts:
    - moby:127.0.0.1
    ports:
    - ${KAFKA_PORT}

  zookeeper:
    image: zookeeper:3.4

volumes:
  data-volume:
  deployment-volume:
  mvn-repo-volume: