version: '3.4'

services:
  switchboard:
    container_name: vre_switchboard_1
    build: ./docker
    working_dir: /usr/local/switchboard
    command: ./docker/docker-run-switchboard.sh
    tty: true
    extra_hosts:
    - moby:127.0.0.1
    ports:
    - 9010:8080
    depends_on:
    - kafka
    volumes:
    - ./:/usr/local/switchboard
    # share maven repository of host:
    - ${HOME}/.m2/repository:/root/.m2/repository
    - data-volume:/usr/local/nextcloud
    - deployment-volume:/tmp/deployment
    environment:
      SWITCHBOARD_TOPIC_NAME: ${SWITCHBOARD_TOPIC_NAME}
      NEXTCLOUD_TOPIC_NAME: ${NEXTCLOUD_TOPIC_NAME}
      KAFKA_PORT: ${KAFKA_PORT}
      NEXTCLOUD_VOLUME: ${SWITCHBOARD_NEXTCLOUD_VOLUME}
      DEPLOYMENT_VOLUME: ${SWITCHBOARD_DEPLOYMENT_VOLUME}
      TEST_USER: ${TEST_USER}
      TEST_PASSWORD: ${TEST_PASSWORD}
      APP_KEY_SERVICES: ${APP_KEY_SERVICES}
      APP_KEY_OBJECTS: ${APP_KEY_OBJECTS}
      USER_TO_LOCK_WITH: ${SWITCHBOARD_USER_TO_LOCK_WITH}
      USER_TO_UNLOCK_WITH: ${SWITCHBOARD_USER_TO_UNLOCK_WITH}

  kafka:
    image: wurstmeister/kafka:1.0.0
    depends_on:
    - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    extra_hosts:
    - moby:127.0.0.1
    ports:
    - ${KAFKA_PORT}

  zookeeper:
    image: zookeeper:3.4

volumes:
  data-volume:
  deployment-volume: